### ISSUE TITLE
Redirection to the incorrect locale

### ISSUE THREAD

**Issue by srna-ms** [microsoftgraph/msgraph-training-pythondjangoapp#52] opened 2021-03-23 17:52 UTC
### Describe the bug

The bug is in the hosted page at https://docs.microsoft.com/en-us/graph/tutorials/python
When I access the Python quick start from the tip, it redirects to the ru-ru localised page instead of en-us

### To Reproduce

1. Go to https://docs.microsoft.com/en-us/graph/tutorials/python
1. Click on Python quick start
1. It opens the Russian language site - https://developer.microsoft.com/ru-ru/graph/quick-start?platform=option-Python

### Expected behavior

The expectation was that in step 3 above the redirection will happen to https://developer.microsoft.com/en-us/graph/quick-start?platform=option-Python respecting the localisation of the previous url
### Desktop

- OS: Windows 10
- Browser Edge Chromium
- Version 91.0.831.0

**Comment by jasonjoh** [comment] 2021-04-21 21:00
Checking with our localization team. The guidance has been for us to leave out any language identifiers in links to MS sites. I don't reproduce what you're seeing, but I always view sites in en-us. I'm guessing either your browser is set with ru-ru as the default, or the last language you viewed developer.microsoft.com was ru-ru.

**Comment by srna-ms** [comment] 2021-04-22 15:21
When I did the same steps above, I got redirected to en-us site.  Did some more digging and figured out that this is what is happening
The locale that I am seeing depends on the last visited locale for this page.  So, when I click on the hard coded ru-ru once and then repeat the steps above, it moves me to ru-ru.  If I click on the en-us and repeat the steps, it moves me to en-us.
What is still puzzling is why it happened the first time since I have no reason to visit Russian documentation (I don't speak the language)

**Comment by jasonjoh** [comment] 2021-04-22 15:42
Thanks for confirming. I checked with our localization team and this is basically a limitation of going between two sites (from docs.microsoft.com -> developer.microsoft.com). The developer.microsoft.com site stores a cookie with your selected language, so when you follow a link to that site that does not hard-code a language, it uses that. We're required to leave out language specifiers so that the site can respect your choice.

I agree it's odd that your first time ended up with ru-ru and can only speculate. Since there's nothing I can do in this repository to change the behavior, I'm going to go ahead and close the issue. I have provided the feedback to our localization team.

**Closed** 2021-04-22 15:42 UTC
Labels: out of scope
